version: 2
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    # - ./scripts/manpages.sh
    # - ./scripts/completions.sh

builds:
  -
    id: simple_api_gateway
    binary: simple_api_gateway
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.buildTime={{ .Date }}
      - -X main.gitCommit={{ .FullCommit }}
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - "386"
      - amd64
      - arm64
    overrides:
      - goos: darwin
        goarch: amd64
        ldflags:
          - -s -w
        env:
          - CGO_ENABLED=0
      - goos: darwin
        goarch: arm64
        ldflags:
          - -s -w
        env:
          - CGO_ENABLED=0
      - goos: linux
        goarch: amd64
        ldflags:
          - -s -w -extldflags "-static"
          - -X main.version={{ .Version }}
          - -X main.buildTime={{ .Date }}
          - -X main.gitCommit={{ .FullCommit }}
      - goos: linux
        goarch: arm64
        ldflags:
          - -s -w -extldflags "-static"
          - -X main.version={{ .Version }}
          - -X main.buildTime={{ .Date }}
          - -X main.gitCommit={{ .FullCommit }}
      - goos: linux
        goarch: "386"
        ldflags:
          - -s -w -extldflags "-static"
          - -X main.version={{ .Version }}
          - -X main.buildTime={{ .Date }}
          - -X main.gitCommit={{ .FullCommit }}
      - goos: windows
        goarch: amd64
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: amd64
      - goos: freebsd
        goarch: "386"
      - goos: freebsd
        goarch: arm64


archives:
  -
    id: simple_api_gateway_archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["tar.gz"]
    files:
      - .qoder/repowiki/zh/**
    format_overrides:
      - goos: windows
        formats: ["zip"]
    ids:
      - simple_api_gateway

nfpms:
  - 
    id: simple_api_gateway_packages
    package_name: simple_api_gateway
    ids:
      - simple_api_gateway
    vendor: nerdneilsfield
    homepage:  https://github.com/nerdneilsfield/simple_api_gateway
    maintainer: "dengqqi <dengqqi935@gmail.com>"
    description: "A simple api gateway"
    license: BSD-3-Clause
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./scripts/systemctl/simple-api-gateway@.service
        dst: /lib/systemd/system/simple-api-gateway@.service
        type: config
        packager: deb
      - src: ./scripts/systemctl/simple-api-gateway@.service
        dst: /usr/lib/systemd/system/simple-api-gateway@.service
        type: config
        packager: rpm
      - src: scripts/rc/simple_api_gateway
        dst: /etc/init.d/simple_api_gateway
        type: config
        packager: apk
    scripts:
      postinstall: ./scripts/post-install.sh
      postremove: ./scripts/post-remove.sh

release:
  github:
    owner: nerdneilsfield
    name: simple_api_gateway

dockers_v2:
  - id: simple-api-gateway
    dockerfile: Dockerfile.goreleaser
    ids:
      - simple_api_gateway
    images:
      - nerdneils/simple_api_gateway
      - ghcr.io/nerdneilsfield/simple_api_gateway
    tags:
      - "{{ .Tag }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    extra_files:
      - example_config.toml
      - .qoder/repowiki/zh
    labels:
      "io.artifacthub.package.readme-url": "https://raw.githubusercontent.com/nerdneilsfield/simple_api_gateway/master/README.md"
      "io.artifacthub.package.maintainers": "[{\"name\":\"dengqqi\",\"email\":\"dengqqi935@gmail.com\"}]"
      "io.artifacthub.package.license": "BSD-3-Clause"
      "org.opencontainers.image.description": "A simple api gateway"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.name": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
