port = 8080                                  # Port to listen on / 监听端口
host = "0.0.0.0"                            # Host to bind to / 绑定主机
log_file_path = "/var/log/simple-api-gateway.log"  # Log file path / 日志文件路径

[cache]
enabled = true                              # Enable cache / 启用缓存
use_redis = false                           # Use Redis for caching / 使用Redis缓存
redis_url = ""                              # Redis connection URL / Redis连接URL
redis_db = 0                                # Redis database number / Redis数据库编号
redis_prefix = "api_gateway:"               # Redis key prefix / Redis键前缀

[[route]]
path = "/api"                               # Route path / 路由路径
backends = [                                # Backend service URLs / 后端服务URL列表
  "https://api.example.com",
  "https://api2.example.com",
  "https://api3.example.com"
]
ua_client = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"  # User-Agent / 用户代理
cache_ttl = 300                             # Cache TTL in seconds (0 = no cache) / 缓存有效期（秒，0表示不缓存）
cache_enable = true                         # Enable cache for this route / 为此路由启用缓存 
cache_paths = [                             # Relative paths that can be cached / 可以被缓存的相对路径列表
  "/v1/users",                              # Only cache paths starting with /v1/users / 只缓存以 /v1/users 开头的路径
  "/v1/products",                           # Only cache paths starting with /v1/products / 只缓存以 /v1/products 开头的路径
] 
[route.custom_headers]                      # Custom headers to add to requests / 添加到请求中的自定义头部
X-Custom-Header = "custom-value"            # Example custom header / 示例自定义头部
X-API-Key = "your-api-key"                  # Example API key header / 示例API密钥头部
X-Request-ID = "request-123"                # Example request ID header / 示例请求ID头部
