services:
  # API网关服务
  simple-api-gateway:
    image: nerdneils/simple_api_gateway:latest
    container_name: simple-api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./config-with-redis.toml:/config.toml
    depends_on:
      - redis
    restart: always
    command: serve /config.toml
    networks:
      - api-gateway-network

  # Redis缓存服务
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - api-gateway-network
    command: redis-server --appendonly yes
    sysctls:
      vm.overcommit_memory: 1

networks:
  api-gateway-network:
    driver: bridge

volumes:
  redis-data:
    driver: local 