port = 8080                                  # Port to listen on / 监听端口
host = "0.0.0.0"                            # Host to bind to / 绑定主机
log_file_path = "/var/log/simple-api-gateway.log"  # Log file path / 日志文件路径

[cache]
enabled = true                              # Enable cache / 启用缓存
use_redis = true                            # Use Redis for caching / 使用Redis缓存
redis_url = "redis://localhost:6379"        # Redis connection URL / Redis连接URL
redis_db = 0                                # Redis database number / Redis数据库编号
redis_prefix = "api_gateway:"               # Redis key prefix / Redis键前缀

[[route]]
path = "/hello"                             # Route path / 路由路径
backends = [                                # Backend service URLs / 后端服务URL列表
  "http://localhost:8080",
  "http://localhost:8081",
  "http://localhost:8082"
]
ua_client = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"  # User-Agent / 用户代理
cache_ttl = 60                              # Cache TTL in seconds (0 = no cache) / 缓存有效期（秒，0表示不缓存）
cache_enable = true                         # Enable cache for this route / 为此路由启用缓存
cache_paths = [                             # Relative paths that can be cached / 可以被缓存的相对路径列表
  "/user",                                  # Only cache paths starting with /user / 只缓存以 /user 开头的路径
  "/product",                               # Only cache paths starting with /product / 只缓存以 /product 开头的路径
]

[[route]]
path = "/hello2"                            # Route path / 路由路径
backends = [                                # Backend service URLs / 后端服务URL列表
  "http://localhost:8081",
  "http://localhost:8082"
]
ua_client = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"  # User-Agent / 用户代理
cache_ttl = 0                               # Cache TTL in seconds (0 = no cache) / 缓存有效期（秒，0表示不缓存）
cache_enable = false                        # Disable cache for this route / 为此路由禁用缓存
